





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace C2S
{
    public class Common
    {
        // Message ID that replies to each RMI method. 
        public const Nettention.Proud.RmiID SignUp = (Nettention.Proud.RmiID)1000 + 1;
        public const Nettention.Proud.RmiID LogIn = (Nettention.Proud.RmiID)1000 + 2;
        public const Nettention.Proud.RmiID ChatToAll = (Nettention.Proud.RmiID)1000 + 3;
        public const Nettention.Proud.RmiID ChatToRoom = (Nettention.Proud.RmiID)1000 + 4;
        public const Nettention.Proud.RmiID ChatToPerson = (Nettention.Proud.RmiID)1000 + 5;
        public const Nettention.Proud.RmiID CreateRoom = (Nettention.Proud.RmiID)1000 + 6;
        public const Nettention.Proud.RmiID EnterRoom = (Nettention.Proud.RmiID)1000 + 7;
        public const Nettention.Proud.RmiID ExitRoom = (Nettention.Proud.RmiID)1000 + 8;
        public const Nettention.Proud.RmiID GetRoomDatas = (Nettention.Proud.RmiID)1000 + 9;
        public const Nettention.Proud.RmiID GetClientDatas = (Nettention.Proud.RmiID)1000 + 10;
        public const Nettention.Proud.RmiID GameReady = (Nettention.Proud.RmiID)1000 + 11;
        public const Nettention.Proud.RmiID GameStart = (Nettention.Proud.RmiID)1000 + 12;
        public const Nettention.Proud.RmiID RecordPosition = (Nettention.Proud.RmiID)1000 + 13;
        public const Nettention.Proud.RmiID RecordRotation = (Nettention.Proud.RmiID)1000 + 14;
        // List that has RMI ID.
        public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
            SignUp,
            LogIn,
            ChatToAll,
            ChatToRoom,
            ChatToPerson,
            CreateRoom,
            EnterRoom,
            ExitRoom,
            GetRoomDatas,
            GetClientDatas,
            GameReady,
            GameStart,
            RecordPosition,
            RecordRotation,
        };
    }
}
namespace S2C
{
    public class Common
    {
        // Message ID that replies to each RMI method. 
        public const Nettention.Proud.RmiID SignUpResult = (Nettention.Proud.RmiID)4000 + 1;
        public const Nettention.Proud.RmiID LoginResult = (Nettention.Proud.RmiID)4000 + 2;
        public const Nettention.Proud.RmiID EchoToAll = (Nettention.Proud.RmiID)4000 + 3;
        public const Nettention.Proud.RmiID EchoToRoom = (Nettention.Proud.RmiID)4000 + 4;
        public const Nettention.Proud.RmiID EchoToPerson = (Nettention.Proud.RmiID)4000 + 5;
        public const Nettention.Proud.RmiID CreateRoomResult = (Nettention.Proud.RmiID)4000 + 6;
        public const Nettention.Proud.RmiID EnterRoomResult = (Nettention.Proud.RmiID)4000 + 7;
        public const Nettention.Proud.RmiID ExitRoomResult = (Nettention.Proud.RmiID)4000 + 8;
        public const Nettention.Proud.RmiID GetRoomDatas = (Nettention.Proud.RmiID)4000 + 9;
        public const Nettention.Proud.RmiID GetClientDatas = (Nettention.Proud.RmiID)4000 + 10;
        public const Nettention.Proud.RmiID GameReadyReflection = (Nettention.Proud.RmiID)4000 + 11;
        public const Nettention.Proud.RmiID GameStartReflection = (Nettention.Proud.RmiID)4000 + 12;
        public const Nettention.Proud.RmiID NotifyPosition = (Nettention.Proud.RmiID)4000 + 13;
        public const Nettention.Proud.RmiID NotifyRotation = (Nettention.Proud.RmiID)4000 + 14;
        // List that has RMI ID.
        public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
            SignUpResult,
            LoginResult,
            EchoToAll,
            EchoToRoom,
            EchoToPerson,
            CreateRoomResult,
            EnterRoomResult,
            ExitRoomResult,
            GetRoomDatas,
            GetClientDatas,
            GameReadyReflection,
            GameStartReflection,
            NotifyPosition,
            NotifyRotation,
        };
    }
}







